spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/openvidu_test
log:
  config:
    mode: local
jwt:
  issuer: kkh
  secret_key: test_security